server:
  port: 8080

spring:
  application:
    name: nice-book-pay
  datasource:
    url: jdbc:mysql://43.143.178.226:3306/book?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: nice
    password: KPenJrhhxDAMHHdj
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  data:
    redis:
      host: 43.143.178.226
      port: 6379
      password: nice@Redis6688
      timeout: 3000


# Mybatis Plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.nicebook.nicebookpay.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.nicebook.nicebookpay.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.web: DEBUG
    org.springframework.jdbc: ERROR
    org.mybatis: ERROR
    org.apache.ibatis: ERROR
    com.baomidou.mybatisplus: ERROR
